python adjust_L_training.py --size 96 \
                            --epoch 200 \
                            --batch_size 4 \
                            --fusion_model "weight3" \
                            --A_model "naive_res" \
                            --fusion_layers 1 2 3\
                            --eval_epoch 1 \
                            --gpu_id 3 --n_cpu 1\
                            --adjust_L_loss "rec-grad-spatial" --l_grad 1 --l_spa 10  \
                            --saving_eval_dir "./eval_result/eval_adjustment" \
                            --adjust_model_dir "./model_ckpt/adjust/" \
                            --eval_low "/data/wengjian/low-light-enhancement/Ours/dataset/LOLdataset/eval15/low" \
                            --eval_high "/data/wengjian/low-light-enhancement/Ours/dataset/LOLdataset/eval15/high"\
                            --patch_low "/data/wengjian/low-light-enhancement/Ours/dataset/LOLdataset/our485/low" \
                            --patch_high "/data/wengjian/low-light-enhancement/Ours/dataset/LOLdataset/our485/high" \
                            --milestones 12300 25000 60000 \
                            --min_ratio 1 \
                            --pretrain_unfolding_model_path "/data/wengjian/low-light-enhancement/Ours/pretrained_model/one_step/Hyper-parameter_alpha_beta/alpha1_beta10/HalfDnCNNSER--Illumination_AloneL--A_t_3_RL2_RVGG_RSSIM-10Ltv_gamma0.5_lamda0.5_train_from_scratch_offset0.05_Fnorm_Rtv0.0_Ltv10.0--NEW---one_step_model.pthep2000" \
                            --Decom_model_low_path '/data/wengjian/low-light-enhancement/Ours/pretrained_model/decom/decom-L_supervised-4layers' \
                            --Decom_model_high_path '/data/wengjian/low-light-enhancement/Ours/pretrained_model/decom/decom4layers/decom_onlyHigh_0.1L_2.2gamma_0.1Lawareep340' \
                            --net_L \